version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: web.docker
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
    links:
      - app
  app:
    build:
      context: ./
      dockerfile: app.docker
    volumes:
      - ./:/var/www
    links:
      - mysql
    environment:
      - DB_PORT=33061
      - DB_HOST=localhost
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=dockerApp
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data.sql:/docker-entrypoint-initdb.d/dump.sql

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
       - 8000:80
      volumes:
       - /sessions
      links:
        - mysql:db
